name: Update DaddyLive Playlist

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync with remote master (reset hard)
        run: |
          git fetch origin
          git reset --hard origin/master

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        run: |
          # If your script needs dependencies, install here
          # e.g. pip install -r requirements.txt
          echo "No dependencies to install"

      - name: Run update script
        run: python daddy.py

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes if any
        run: |
          git add DaddyLive.m3u8
          git diff --cached --quiet || git commit -m "Update DaddyLive.m3u8 playlist"

      - name: Push changes to master
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
