name: DaddyLive Playlist Update

on:
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright requests
        playwright install

    - name: Run daddylive.py script
      run: python daddylive.py

    - name: Commit updated playlists (forced)
      run: |
        git config --global user.name "daddybot"
        git config --global user.email "daddybot@users.noreply.github.com"
        git add DaddyLiveRAW.m3u8 DaddyLive.m3u8
        git commit --allow-empty -m "🤝 Handshake + Proxy update"
        git push
