name: Update DaddyLive Playlist

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (adjust if needed)
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install system dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 \
            libgraphene-1.0-0 \
            libwoff2dec-dev \
            libvpx9 \
            libevent-2.1-7 \
            libopus0 \
            libgstreamer-plugins-base1.0-0 \
            libgstreamer1.0-0 \
            libflite1 \
            libavif16 \
            libharfbuzz-icu0 \
            libsecret-1-0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libgles2-mesa-dev \
            libx264-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install requests playwright
          playwright install

      - name: Run Update Script
        run: python update_daddylive.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add DaddyLive.m3u8
          git commit -m "⏱️ Auto-update DaddyLive.m3u8"
          git push
        continue-on-error: true
