name: Update DaddyLive Playlist

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests playwright
          playwright install --with-deps

      - name: Run Update Script
        run: python update_daddylive.py

      - name: Commit and Force Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add DaddyLive.m3u8
          git commit -m "🔁 Auto-update DaddyLive.m3u8" || echo "Nothing to commit"
          git push origin main --force
