name: Update DaddyLive Playlist

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Pull latest changes
      run: git pull origin main

    - name: Run update script
      run: python daddy.py

    - name: Show playlist contents
      run: cat DaddyLive.m3u8

    - name: Check git status
      run: git status

    - name: Show git diff
      run: git diff

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes if any
      run: |
        git add DaddyLive.m3u8
        git diff --cached --quiet || git commit -m "Update DaddyLive.m3u8 playlist"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
