name: Update DaddyLive Playlist

on:
  push:   # Runs on every push

jobs:
  fetch-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Force fetch and save playlist
      run: python daddylive.py
