name: "🔁 Update DrewLive EPG 📺"

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update_epg:
    runs-on: ubuntu-latest

    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "🐍 Set up Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: "📦 Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: "🎯 Run DrewLive EPG merger"
        run: python drewepg.py

      - name: "💾 Commit & Push if EPG Changed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Always pull first to avoid conflicts
          git fetch origin main
          git reset --hard origin/main

          git add DrewLive.xml

          if git diff --cached --quiet; then
            echo "✅ No changes detected — skipping commit."
          else
            git commit -m "🔁 Auto-update DrewLive EPG ($(date -u +'%Y-%m-%d %H:%M UTC'))"
            git push origin main
          fi

      - name: "📦 Upload DrewLive EPG as artifact"
        uses: actions/upload-artifact@v4
        with:
          name: DrewLive-EPG
          path: DrewLive.xml
