name: 🔁 Force Update FSTV Playlist 🚀

on:
  workflow_dispatch:   # 🖐️ Manual trigger
  schedule:
    - cron: '0 * * * *'  # ⏰ Hourly refresh
  push:
    paths:
      - 'fstv.py'       # 🛠️ Only runs on script changes

permissions:
  contents: write        # 🔐 Needed to push changes

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 🧠 Full git history

      - name: 🐍 Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip
          pip install beautifulsoup4 playwright
          python -m playwright install --with-deps

      - name: 🎯 Run playlist generator
        run: python fstv.py

      - name: 💾 Commit & push changes safely
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || true
          git add FSTV24.m3u8
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "🔁 Auto-update FSTV playlist at $timestamp" || echo "🟡 No changes to commit"
          git push --force-with-lease origin main
