name: 🔁 FSTV Stream Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"  # Every 3 hours

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install firefox

      - name: ▶️ Run FSTV scraper
        run: python fstv.py

      - name: 📤 Commit and push updated FSTV.m3u8
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add FSTV.m3u8
          git commit -m "🔄 Update FSTV.m3u8 [auto]" || echo "No changes to commit"
          git push
