name: Force Update FSTV Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    paths:
      - 'fstv.py'

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install beautifulsoup4 playwright
          python -m playwright install --with-deps

      - name: Run playlist generator
        run: python fstv.py

      - name: Commit & push safely
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || true
          git add FSTV24.m3u8 || echo "No file to add"
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update FSTV playlist"
            git push --force-with-lease origin main
          else
            echo "No changes to commit"
          fi
