name: Update FSTV Playlist

on:
  push:
    paths:
      - 'fstv.py'
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Every hour at minute 0

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install beautifulsoup4 playwright

      - name: Install Playwright Browsers
        run: |
          python -m playwright install --with-deps

      - name: Run update script
        run: python fstv.py

      - name: Show file info
        run: |
          ls -l FSTV24.m3u8
          head -20 FSTV24.m3u8

      - name: Commit and push updated playlist if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git stash --include-untracked
          git fetch origin main
          git rebase origin/main
          git stash pop || echo "Nothing to pop"

          if ! git diff FSTV24.m3u8 --quiet; then
            git add FSTV24.m3u8
            git commit -m "Update FSTV24.m3u8 with latest URLs"
            git push origin main
          else
            echo "No changes to commit"
