name: Scrape FSTVLive Playlist

on:
  schedule:
    - cron: '0 * * * *'  # At minute 0 every hour
  workflow_dispatch:      # Manual trigger too

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: |
          python -m pip install --upgrade pip
          pip install requests

      - run: python tims.py

      - uses: actions/upload-artifact@v3
        with:
          name: FSTVLive-playlist
          path: FSTVLive.m3u