name: 🔁 Force Update FSTV Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # ⏰ Hourly refresh
  push:
    paths:
      - 'fstv.py'

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install Dependencies
        run: |
          pip install --upgrade pip
          pip install beautifulsoup4 playwright
          python -m playwright install --with-deps

      - name: ⚙️ Run Scraper
        run: python fstv.py

      - name: 💾 Commit & Push Playlist Safely
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Pull latest changes and rebase to avoid overwriting newer commits
          git pull --rebase origin main || true

          git add FSTV24.m3u8
          git commit -m "🔁 Auto-refresh FSTV playlist at $(date -u)" || echo "🟡 No changes to commit"

          # Random delay to reduce push collisions
          sleep $((RANDOM % 10 + 5))

          # Push safely with lease protection
          git push --force-with-lease origin main
