name: IPTV Scraper Automation

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:        # Allow manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Docker image
        run: docker pull mitrakalloo/thetvapp:latest

      - name: Run scraper container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            mitrakalloo/thetvapp:latest \
            /bin/sh -c "python scraper.py"

      - name: List output files
        run: ls -lh ./

      - name: Print contents of the M3U8 playlist
        run: |
          echo "====== START OF thetvapp.m3u8 ======"
          cat thetvapp.m3u8
          echo "======= END OF thetvapp.m3u8 ======="

      - name: Commit and push updated playlist
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add thetvapp.m3u8
          git diff --staged --quiet || git commit -m "Update IPTV playlist"
          git push