name: Update TVPlaylists

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

env:
  url1: http://192.168.0.28:8090/thetvapp/playlist?quality=hd
  file1: thetvapp.m3u8
  url2: http://192.168.0.28:8090/tvpass/playlist?quality=hd
  file2: tvpass.m3u8
  merged: merged.m3u8

jobs:
  update_playlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for git diff to work properly

      - name: Download thetvapp playlist
        run: |
          curl -sSL "$url1" -o "$file1"
          echo "--- $file1 preview ---"
          head -n 10 "$file1"

      - name: Download tvpass playlist
        run: |
          curl -sSL "$url2" -o "$file2"
          echo "--- $file2 preview ---"
          head -n 10 "$file2"

      - name: Merge playlists
        run: |
          echo "#EXTM3U" > "$merged"
          tail -n +2 "$file1" >> "$merged"
          tail -n +2 "$file2" >> "$merged"
          echo "--- $merged preview ---"
          head -n 10 "$merged"

      - name: Commit and push if any playlist changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add "$file1" "$file2" "$merged"
          git diff --cached --quiet || git commit -m "Update TVPlaylists"
          git push
