name: IPTV Scraper Automation

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest Docker image
        run: docker pull mitrakalloo/thetvapp:latest

      - name: Run scraper container and copy output
        run: |
          echo "Running scraper inside container..."
          mkdir -p ${{ github.workspace }}/output

          timeout 180s docker run --rm \
            -v ${{ github.workspace }}/output:/usr/src/app/output \
            mitrakalloo/thetvapp:latest \
            /bin/sh -c "node dist/index.js && cp thetvapp.m3u8 output/thetvapp.m3u8" \
            > thetvapp.log 2>&1 || echo "Scraper timed out or exited with error"

          echo "--- Scraper Logs ---"
          cat thetvapp.log || echo "No log output available"

      - name: List all output files
        run: ls -R ./output || echo "Output folder empty"

      - name: Move playlist to repo root (optional)
        run: |
          if [ -f ./output/thetvapp.m3u8 ]; then
            mv ./output/thetvapp.m3u8 .
          else
            echo "Playlist not found in output!"
          fi

      - name: Commit and push updated playlist
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          if [ -f thetvapp.m3u8 ]; then
            git add thetvapp.m3u8
            git diff --staged --quiet || git commit -m "Update IPTV playlist"
            git push
          else
            echo "No playlist file found. Skipping commit."
