name: thetvapp

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:         # Manual trigger

env:
  m_filename: thetvapp.m3u8
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch_m3u8_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # <-- Needed to allow push to work properly

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install aiohttp beautifulsoup4

      - name: Run Python script from remote
        run: |
          curl -sSL -o thetvapp-scraper.py "${{ secrets.THETVAPP_URL }}"
          python thetvapp-scraper.py

      - name: Verify M3U8 output
        run: |
          if [ -f "${{ env.m_filename }}" ]; then
            echo "::notice file=${{ env.m_filename }}::Download succeeded"
            cat "${{ env.m_filename }}" | head -n 20
          else
            echo "::error ::${{ env.m_filename }} not found"
            exit 1
          fi

      - name: Commit and push if file changed
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"

          git add "${{ env.m_filename }}"
          git diff --cached --quiet || git commit -m "Update M3U8 playlist"
          git push