name: Update Kodi Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Reset to origin/main
      run: |
        git fetch origin
        git reset --hard origin/main

    - name: Run Kodi Playlist Script
      run: |
        # Your playlist-generating script here
        python3 your_script.py

    - name: Commit and Push Changes
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add MergedPlaylist_Kodi.m3u8
        git commit -m "Auto-update Kodi formatted playlist" || echo "No changes to commit"
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git main --force
