name: Update Kodi Playlist

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run Kodi Playlist Generator
        run: python kodi.py

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Pull latest changes first to avoid non-fast-forward errors
          git pull origin main --rebase || true

          # Stage and commit if there are changes
          git add MergedPlaylist_Kodi.m3u8
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update Kodi formatted playlist"
            git push origin main
          fi
