name: Convert to Kodi Format

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for full git history

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Kodi Conversion Script
        run: python kodi.py

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit if Needed
        run: |
          git add MergedPlaylist_Kodi.m3u8
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Auto-update Kodi formatted playlist"

      - name: Rebase and Push
        run: |
          git pull --rebase --autostash origin main
          git push origin main
