name: Convert to Kodi Format

on:
  schedule:
    - cron: "*/30 * * * *"  # Run every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Kodi Conversion Script
        run: python kodi.py

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync with remote main branch forcibly
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Commit and push updated playlist if changed
        run: |
          git add MergedPlaylist_Kodi.m3u8
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update Kodi formatted playlist"
            git push origin main
          else
            echo "No changes to commit"
          fi
