name: 🔄 Auto Update Merged Clean IPTV Playlist

on:
  push:
    branches:
      - main
    paths:
      - 'mergeclean.py'
      - '.github/workflows/mergeclean.yml'
  schedule:
    - cron: '0 * * * *'
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: 🐍 Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install dependencies
        run: pip install requests

      - name: 🧠 Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: ▶️ Run mergeclean.py script
        run: python mergeclean.py

      - name: 🔄 Sync local branch to remote to avoid stale push error
        run: |
          git fetch origin main
          git reset origin/main --hard

      - name: 📂 Stage & commit updated playlist
        run: |
          git add MergedCleanPlaylist.m3u8

          # Only commit if there are real changes
          git diff --cached --quiet && {
            echo "⚠️ No changes to commit. Skipping push.";
            exit 0;
          }

          git commit -m "📝 Auto-update merged clean IPTV playlist at $(date -u)"

      - name: ⏳ Random delay before push to reduce collisions
        run: sleep $((RANDOM % 10 + 5))

      - name: 🚀 Force push with lease to avoid stale conflicts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push --force-with-lease origin main
