name: 🔄 Auto Update Merged IPTV Playlist

on:
  push:
    branches:
      - main
    paths:
      - 'MergedPlaylist.m3u8'
      - 'iptv.py'
  schedule:
    - cron: '0 * * * *'
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install Python dependencies
        run: pip install requests

      - name: 🧠 Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: ▶️ Run IPTV merging script
        run: python iptv.py

      - name: 💾 Force add and commit, even if unchanged
        run: |
          git add MergedPlaylist.m3u8
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "📝 Force update of merged playlist at $timestamp" || echo "No changes to commit"

      - name: 🚀 Force push to origin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push --force origin main
