name: 🔄 Auto Update Merged IPTV Playlist

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'MergedPlaylist.m3u8'
      - 'iptv.py'

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout fresh repository (no cache, no stale state)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Only the latest commit, no full history

      - name: 🐍 Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install Python dependencies
        run: pip install requests

      - name: 🧠 Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: ▶️ Run IPTV merging script
        run: |
          echo "# Last forced update: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" > MergedPlaylist.m3u8
          python iptv.py

      - name: 🧼 Clean Git state (optional, makes sure no junk is hanging around)
        run: git reset --hard HEAD

      - name: 💾 Commit with timestamp
        run: |
          git add MergedPlaylist.m3u8
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "📝 Forced update at $timestamp" || echo "Nothing to commit."

      - name: 🚀 Force push without any pull (overwrite everything)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push --force origin main
