name: Update Playlist

on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This is important!

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/Drewski2423/DrewLive.git
          git pull origin main --rebase

      - name: Update the playlist
        run: |
          echo "#EXTM3U" > MergedPlaylist.m3u8
          # Your merging logic here

      - name: Commit changes
        run: |
          git add MergedPlaylist.m3u8
          git commit -m "Auto-update merged playlist" || echo "No changes to commit"

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push origin HEAD:main
