name: Auto-Update Merged IPTV Playlist

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Run IPTV script
        run: python iptv.py

      - name: Configure Git
        run: |
          git config user.name "Drewski2423"
          git config user.email "andrew.rocha06@gmail.com"

      - name: Fetch latest and reset
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Commit and force push updated playlist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add MergedPlaylist.m3u8
          git diff --cached --quiet || git commit -m "Auto-update merged playlist"
          git push --force https://x-access-token:${GH_TOKEN}@github.com/Drewski2423/DrewLive.git HEAD:main
