name: Auto Update Merged IPTV Playlist

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # every hour at minute 0 UTC

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests

      - name: Run IPTV merging script
        run: python iptv.py

      - name: Commit and push merged playlist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add MergedPlaylist.m3u8
          git diff --cached --quiet || git commit -m "Auto-update merged IPTV playlist"
          git push origin main
        shell: bash
        continue-on-error: true
