name: 🔄 Auto Update Merged IPTV Playlist

on:
  push:
    branches:
      - main
    paths:
      - 'MergedPlaylist.m3u8'
      - 'iptv.py'
  schedule:
    - cron: '0 * * * *'
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install Python dependencies
        run: pip install requests

      - name: 🧠 Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 🔃 Pull latest changes with rebase
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/Drewski2423/DrewLive.git
          git pull origin main --rebase

      - name: ▶️ Run IPTV merging script
        run: python iptv.py

      - name: 💾 Force commit even if no content diff
        run: |
          git add MergedPlaylist.m3u8
          git commit -m "📝 Forced update of merged playlist" || echo "No changes to commit"

      - name: 🚀 Force push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push --force origin main
