name: Update PPVLand Playlist

on:
  schedule:
    - cron: '0 * * * *'  # Every hour on the hour (UTC)
  workflow_dispatch:       # Optional manual run

jobs:
  update-ppvland-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ⬇️ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install firefox

      - name: ▶️ Run scraper script
        run: python ppv.py  # Change if your script filename differs

      - name: 📤 Force commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add PPVLand.m3u8
          git commit -m "🔄 Auto-update PPVLand.m3u8" || echo "No changes to commit"
          git push origin HEAD --force
