name: ♻️ Generate PPVLand Playlist

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:        # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright aiohttp
          playwright install firefox

      - name: 🚀 Run script
        run: python ppv.py

      - name: 💾 Commit and push updated playlist
        run: |
          git config --global user.name "daddybot"
          git config --global user.email "bot@daddy.live"
          git add PPVLand.m3u8
          git commit -m "🤖 Auto update PPVLand.m3u8 [forced]" || echo "No changes to commit"
          git push
