name: 🕵️‍♂️ PPV Update Playlist

on:
  workflow_dispatch:       # Manual trigger
  schedule:
    - cron: '*/30 * * * *' # Every 30 minutes

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: ⚙️ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright aiohttp
          npx playwright install --with-deps

      - name: 🚀 Run scraper script
        run: python ppv.py

      - name: 📝 Commit and push updated playlist
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action 🤖"
          git add PPVLand.m3u8
          git diff --cached --quiet || (
            git commit -m "🤖 Auto update PPVLand.m3u8 [forced]"
            git push
          )
        shell: bash
