name: 🚀 PPV Scraper & Playlist Update

on:
  schedule:
    - cron: '*/30 * * * *'  # ⏰ Every 30 minutes
  workflow_dispatch:       # 🔥 Manual trigger

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    env:
      DEBUG: "pw:api"       # 🕵️‍♂️ Playwright debug logs
    steps:
    - name: 📥 Checkout repo
      uses: actions/checkout@v3

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: 📦 Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright aiohttp

    - name: 🎭 Install Playwright browsers & dependencies
      uses: microsoft/playwright-github-action@v1

    - name: 🏃 Run PPV scraper script
      run: |
        python ppv.py

    - name: 🧹 Configure git user for commit
      run: |
        git config user.name "daddybot 🤖"
        git config user.email "daddybot@example.com"

    - name: 📝 Commit and push changes
      run: |
        git add PPVLand.m3u8
        git commit -m "🤖 Auto update PPVLand.m3u8 [forced]"
        git push
      continue-on-error: true   # 🚨 Prevent fail if nothing to commit or push issues
