name: 🚀 Update PPVLand Playlist 📺

on:
  schedule:
    - cron: '0 * * * *'  # Every hour on the hour (UTC)
  workflow_dispatch:       # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Pull full history for force push

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright urllib3 aiohttp
          playwright install firefox
          playwright install-deps

      - name: 🎯 Run scraping script
        run: python ppv.py

      - name: 💾 Commit & force-push playlist
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase  # Ensure latest
          git add PPVLand.m3u8
          git commit -m "Force update PPVLand playlist $(date -u)" || echo "No changes to commit"
          git push origin main --force
