name: Update PPV Playlist

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours at minute 0
  workflow_dispatch:        # manual trigger support

jobs:
  update-ppv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright aiohttp
        playwright install firefox

    - name: Run ppv.py script
      run: python ppv.py

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and force push changes
      run: |
        git add PPVLand.m3u8
        git commit -m "Auto update of PPV playlist" || echo "No changes to commit"
        git push -f origin HEAD:${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
