name: Update PPV Playlist

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:        # Manual trigger

permissions:
  contents: write           # Required for pushing commits

jobs:
  update-ppv-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install dependencies
        run: pip install playwright aiohttp && playwright install firefox

      - name: 🔄 Run PPV scraping script
        run: python ppv.py

      - name: 🕒 Inject timestamp to force commit
        run: |
          echo "# Updated at $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> PPVLand.m3u8

      - name: 💾 Commit and push updated PPVLand.m3u8
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add PPVLand.m3u8
          git commit -m "Auto update of PPV playlist" || echo "No changes to commit"
          git push origin main
