name: 🕵️‍♂️ Scrape & Commit Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: ⚙️ Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright aiohttp

      - name: 🔧 Install Playwright browsers
        run: npx playwright install --with-deps

      - name: 🚀 Run scraper script
        run: python ppv.py

      - name: 📝 Commit & push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action 🤖"
          git add PPVLand.m3u8
          git diff --cached --quiet || (
            git commit -m "🤖 Auto update PPVLand.m3u8"
            git push
          )
        shell: bash
