name: Update SportsWebcast Playlist

on:
  workflow_dispatch:  # Manual run from GitHub UI
  schedule:
    - cron: "0 * * * *"  # ⏰ Every hour on the hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Requests
        run: pip install requests

      - name: Build SportsWebcast.m3u
        run: |
          python3 <<EOF
          import requests
          import re

          sources = {
              "NBA": "https://iptv-scraper-re.vercel.app/nbawebcast",
              "MLB": "https://iptv-scraper-re.vercel.app/mlbwebcast",
              "NFL": "https://iptv-scraper-re.vercel.app/nflwebcast",
              "NHL": "https://iptv-scraper-re.vercel.app/nhlwebcast",
          }

          epg_url = "https://tinyurl.com/dummy2423-epg"
          output_lines = [f'#EXTM3U url-tvg="{epg_url}"']

          for group, url in sources.items():
              print(f"Fetching: {url}")
              r = requests.get(url)
              lines = r.text.strip().splitlines()
              for line in lines:
                  if line.startswith("#EXTINF"):
                      if 'group-title="' in line:
                          line = re.sub(r'group-title=".*?"', f'group-title="{group}"', line)
                      else:
                          line = line.replace("#EXTINF:-1", f'#EXTINF:-1 tvg-id="Sports.Dummy.us" group-title="{group}"')
                      output_lines.append(line)
                  elif not line.startswith("#EXTM3U"):
                      output_lines.append(line)

          with open("SportsWebcast.m3u", "w", encoding="utf-8") as f:
              f.write("\n".join(output_lines))
          EOF

      - name: Commit and Push Updated M3U
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add SportsWebcast.m3u
          git commit -m "🔁 Auto-update SportsWebcast.m3u" || echo "No changes to commit"
          git push
