name: 🚀 Update StreamedSU Playlist 📺

on:
  schedule:
    - cron: '0 */2 * * *'  # ⏰ Every 2 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright urllib3 aiohttp
          playwright install firefox
          playwright install-deps

      - name: 🎯 Run scraping script
        run: python streamsu.py

      - name: 🕒 Inject timestamp to guarantee change
        run: |
          sed -i '/^# Updated at/d' StreamedSU.m3u8
          echo "# Updated at $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> StreamedSU.m3u8

      - name: 💾 Commit & Safely Push if Playlist Changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git reset --hard origin/main

          git add StreamedSU.m3u8

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
            exit 0
          fi

          git commit -m "🔁 Updated StreamedSU.m3u8 @ $(date -u)"

          # Delay to reduce conflict chance with other workflows
          sleep $((RANDOM % 10 + 5))

          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git pull --rebase origin main || exit 1
          git push origin main
