name: 🚀 Update StreamedSU Playlist 📺

on:
  schedule:
    - cron: '0 * * * *'  # Every hour on the hour (UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright urllib3 aiohttp
          playwright install firefox
          playwright install-deps

      - name: 🎯 Run scraping script
        run: python streamsu.py

      - name: 🐛 Debug: Show playlist output
        run: |
          echo "=== Playlist Contents ==="
          cat StreamedSU.m3u8 || echo "File missing!"
          echo
          ls -lh StreamedSU.m3u8
          git status
          git diff

      - name: 💾 Commit & push playlist if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add StreamedSU.m3u8
          git reset .github/workflows/ || true
          if ! git diff --cached --quiet; then
            git commit -m "Update playlist $(date -u)"
            git push --force origin main
          fi
