name: 🚀 Force Update StreamEast Playlist 📺

on:
  schedule:
    - cron: '0 * * * *'  # ⏰ Every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  force-update:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright urllib3 aiohttp
          playwright install firefox
          playwright install-deps

      - name: 🎯 Run scraping script
        run: python stream.py

      - name: 🕒 Append unique timestamp (forces commit)
        run: |
          sed -i '/^# Updated at/d' StreamEast.m3u8
          echo "# Updated at $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> StreamEast.m3u8

      - name: 💾 Commit & push with force-with-lease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git reset --hard origin/main

          git add StreamEast.m3u8

          git commit -m "🔁 Forced update StreamEast @ $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "🟡 Nothing to commit"

          sleep $((RANDOM % 10 + 5))

          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push --force-with-lease origin main
