name: 🚀 Update StreamedSU Playlist 📺

on:
  schedule:
    - cron: '0 */2 * * *'  # every 2 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies & Playwright browsers
        run: |
          python -m pip install --upgrade pip
          pip install playwright urllib3 aiohttp
          playwright install firefox
          playwright install-deps

      - name: 🎯 Run scraping script
        run: python streamsu.py
        timeout-minutes: 10  # optional timeout to fail fast if it hangs

      - name: 💾 Commit & push if playlist changed safely
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

          # Pull latest changes without rebase or reset
          git pull origin main

          # Add the playlist file changed by the scraper
          git add StreamedSU.m3u8

          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "✅ No changes in playlist"
            exit 0
          else
            git commit -m "🔁 Update playlist $(date -u)"
          fi

          # Push the changes (normal push)
          git push origin main
