name: 🚀 Update StreamedSU Playlist 📺

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies & Playwright browsers
        run: |
          python -m pip install --upgrade pip
          pip install playwright urllib3 aiohttp
          playwright install firefox
          playwright install-deps

      - name: 🎯 Run scraping script
        run: python streamsu.py

      - name: 💾 Commit & push if playlist changed safely
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git reset .github/workflows/ || true

          # Pull latest changes and rebase to avoid overwriting newer commits
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git pull --rebase origin main || true

          git add StreamedSU.m3u8

          if git diff --cached --quiet; then
            echo "✅ No changes in playlist"
            exit 0
          else
            git commit -m "🔁 Update playlist $(date -u)"
          fi

          # Random sleep to reduce push collisions
          sleep $((RANDOM % 10 + 5))

          git push --force-with-lease origin main
