name: 🚀 Update TheTVApp Playlist 📺

on:
  schedule:
    - cron: '0 * * * *'  # ⏰ Every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 📦 Install dependencies
        run: pip install -r requirements.txt

      - name: 🧼 Stash any local changes (clean slate)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git stash || true
          git pull --ff-only || true

      - name: ▶️ Run scraper
        run: python streamsu.py

      - name: 📡 Commit updated playlist
        run: |
          git add TheTVApp.m3u8
          git commit -m "🔁 Update playlist $(date -u +'%a %b %d %T UTC %Y')" || echo "No changes to commit"

      - name: ⬆️ Push to repo (force to avoid conflict)
        run: git push origin main
