name: Update TheTVApp Playlist

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:        # Allows manual run from GitHub UI

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run update script
        run: python thetvapp.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add TheTVApp.m3u8
          git diff --cached --quiet || git commit -m "Auto-update TheTVApp.m3u8"

          # Pull remote changes and rebase local commits on top
          git pull --rebase origin main

          # Push your changes
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
