name: 🚀 Update TheTVApp Playlist 📺

on:
  schedule:
    - cron: '0 * * * *'   # Every hour 🕒
  workflow_dispatch:      # Manual trigger ✋

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository (full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright urllib3 aiohttp
          playwright install firefox
          playwright install-deps

      - name: 🎯 Run scraping script
        run: python tv.py

      - name: 💾 Commit & force-push if changed
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we're in the repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase
          git add TheTVApp.m3u8
          git commit -m "Update TheTVApp playlist $(date -u)" || echo "No changes"
          git push --force origin main
