name: Update TheTVApp Playlist

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:        # Manual trigger

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          pip install -r requirements.txt || true  # optional

      - name: Run update script
        run: python update_playlist.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add TheTVApp.m3u8
          git commit -m "Auto-update TheTVApp.m3u8"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}