name: 🚀 Update TheTVApp Playlist 📺

on:
  schedule:
    - cron: '0 * * * *'   # Every hour 🕒
  workflow_dispatch:      # Manual trigger ✋

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies + Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright urllib3 aiohttp
          playwright install firefox
          playwright install-deps

      - name: 🎯 Run scraper
        run: |
          set -e
          python tv.py

      - name: 🧪 Debug: show diff if any
        run: |
          echo "Checking git status..."
          git status
          git diff

      - name: 💾 Commit & force-push playlist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add TheTVApp.m3u8
          git commit -m "Update playlist at $(date -u)" || echo "No changes to commit"
          git push --force origin main
