name: 🔄 Update Tims247 Playlist

on:
  schedule:
    - cron: '*/5 * * * *'  # ⏱ Auto update every 5 minutes
  workflow_dispatch:        # ✅ Manual trigger

permissions:
  contents: write           # ✅ Required to push changes

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # Full history for git pull --rebase
          persist-credentials: true  # Allow pushing using GITHUB_TOKEN

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install Python dependencies
        run: pip install --upgrade pip requests

      - name: 🔄 Run update script
        run: |
          set -e
          echo "Running tim.py..."
          python tim.py

      - name: 🕒 Append timestamp to ensure commit
        run: echo "# Updated at $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> Tims247.m3u8 || true

      - name: 💤 Sleep random delay (to reduce collision)
        run: sleep $((RANDOM % 10 + 5))

      - name: 🔃 Pull latest changes with rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git pull --rebase origin main

      - name: 🧠 Configure Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: 💾 Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Tims247.m3u8
          git diff --cached --quiet && echo "✅ No changes to commit" && exit 0
          git commit -m "🔄 Updated Tims247.m3u8 @ $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push origin main
