name: 🔄 Update Tims247 Playlist

on:
  schedule:
    - cron: '*/5 * * * *'  # ⏱ Auto update every 5 minutes
  workflow_dispatch:        # ✅ Manual trigger

permissions:
  contents: write           # ✅ Required to push changes

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # Full history for git pull --rebase

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install Python dependencies
        run: pip install --upgrade pip requests

      - name: 🔄 Run update script
        run: |
          echo "Running tim.py..."
          python tim.py || { echo "❌ tim.py failed"; exit 1; }

      - name: 🕒 Append timestamp to ensure commit
        run: |
          echo "# Updated at $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> Tims247.m3u8 || true

      - name: 🧠 Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: 🔃 Pull latest changes with rebase
        run: |
          git pull --rebase origin main || {
            echo "⚠️ Rebase failed. Continuing without it.";
          }

      - name: 💾 Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Tims247.m3u8
          git diff --cached --quiet && echo "✅ No changes to commit" && exit 0
          git commit -m "🔄 Updated Tims247.m3u8 @ $(date -u +'%Y-%m-%d %H:%M:%S')"
          sleep $((RANDOM % 10 + 5))  # Avoid collision on frequent commits
          git push origin main
