name: 🔄 Update Tims247 Playlist

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 🎯 Run scraping script
        run: python tim.py

      - name: 💾 Commit & Push if Playlist Changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Tims247.m3u8

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
            exit 0
          fi

          git commit -m "🔁 Update playlist $(date -u +'%a %b %d %T UTC %Y')"

          if ! git push origin main; then
            echo "⚠️ Push rejected, pulling and rebasing..."
            git pull --rebase origin main || {
              echo "❌ Rebase failed, aborting."
              exit 1
            }
            git push origin main || {
              echo "❌ Push failed again after rebase."
              exit 1
            }
          fi
