name: 🎯 Update Tims Playlist

on:
  workflow_dispatch: 
  schedule:             
    - cron: "0 * * * *"   

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 📦 Install dependencies
        run: pip install requests pycryptodome

      - name: 🛠️ Run tims.py Script
        run: python tims.py

      - name: 💾 Commit & Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          # Sync with remote changes before pushing
          git pull
          git add Tims247.m3u8
          git commit -m "🔄 Update Tims247.m3u8" || echo "ℹ️ No changes to commit"
          git push
