name: ⚽🏀🏈 Update TopEmbed Playlist 📺

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright tqdm
          playwright install-deps
          playwright install

      - name: 🎯 Run TopEmbed Scraper
        run: python topembed.py

      - name: 💾 Commit & Push if Playlist Changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage generated playlist
          git add topembed_playlist.m3u8

          # Check for changes
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
            exit 0
          fi

          git commit -m "🔁 Update TopEmbed playlist $(date -u +'%a %b %d %T UTC %Y')"

          # Add random sleep to prevent race conditions
          sleep $((RANDOM % 10 + 5))

          # Push safely with fallback merge
          if ! git push origin main; then
            echo "⚠️ Push rejected. Trying safe fetch + rebase..."
            git pull origin main --rebase || {
              echo "❌ Rebase failed. Exiting to avoid corruption."
              exit 1
            }
            git push origin main || {
              echo "❌ Second push failed. Remote may have changed again."
              exit 1
            }
          fi
