name: 🔄 Force Update TVPass Playlist

on:
  schedule:
    - cron: '*/30 * * * *'  # ⏱ Every 30 minutes
  workflow_dispatch:        # 🔘 Manual trigger

permissions:
  contents: write           # ✅ Required for pushing commits

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install dependencies
        run: pip install requests

      - name: ▶️ Run TVPass playlist update script
        run: python tvpass.py

      - name: 🕒 Add timestamp to force commit
        run: |
          echo "# Updated at $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> TVPass.m3u

      - name: 💾 Commit and safely push TVPass.m3u if changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git fetch origin main
          git reset origin/main --hard

          git add TVPass.m3u

          git commit -m "🔁 Force update TVPass.m3u on $(date -u)" || echo "🟡 No changes to commit"

          git push --force-with-lease origin main
