name: Update UDPTV Playlist

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:        # Manual trigger support

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository on main branch
        uses: actions/checkout@v3
        with:
          ref: main   # explicitly checkout main branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run UDPTV playlist update script
        run: python udptv.py

      - name: Force-inject timestamp to guarantee diff
        run: |
          echo "# Updated at $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> UDPTV.m3u

      - name: Commit and push updated playlist every time
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git pull origin main --rebase  # Pull and rebase to integrate remote changes
          git add UDPTV.m3u
          git commit -m "Force update UDPTV.m3u with timestamp" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
