name: 🏈🏒⚾ Update SportsWebcast Playlist 📺

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp beautifulsoup4 lxml playwright urllib3
          playwright install --with-deps chromium

      - name: 🎯 Run scraping script
        run: python webcast.py

      - name: 💾 Commit & Safely Push if Playlist Changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add SportsWebcast.m3u8

          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
            exit 0
          fi

          git commit -m "🔁 Update playlist $(date -u +'%a %b %d %T UTC %Y')"
          sleep $((RANDOM % 10 + 5))

          if ! git push origin main; then
            echo "⚠️ Push rejected. Trying safe fetch + merge..."
            git pull origin main --rebase || {
              echo "❌ Rebase failed. Exiting."
              exit 1
            }
            git push origin main || {
              echo "❌ Second push failed."
              exit 1
            }
          fi
