name: 🏈🏒🏀 Update Webcast Playlists 📺

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python and Playwright dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          playwright install --with-deps

      - name: 🎯 Run scraping script
        run: python webcast.py

      - name: 💾 Commit & Push if Playlists Changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add NFLWebcast.m3u8 NHLWebcast.m3u8
          git stash push -m "autogenerated playlists"
          git pull --rebase origin main || true
          git stash pop || true
          if git diff --quiet; then
            exit 0
          fi
          git commit -m "🔁 Update playlists $(date -u +'%a %b %d %T UTC %Y')"
          git push origin main
